branch 'main' set up to track 'origin/main'.
(.venv) PS D:\Sigma6.0\SIH\Final\Lens\Lens\LensClone\backend> touch data_preprocessor.py
(.venv) PS D:\Sigma6.0\SIH\Final\Lens\Lens\LensClone\backend> python data_preprocessor.py
Traceback (most recent call last):
  File "D:\Sigma6.0\SIH\Final\Lens\Lens\LensClone\backend\data_preprocessor.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
(.venv) PS D:\Sigma6.0\SIH\Final\Lens\Lens\LensClone\backend> pip i pandas
ERROR: unknown command "i"
(.venv) PS D:\Sigma6.0\SIH\Final\Lens\Lens\LensClone\backend> pip install pandas
Collecting pandas
  Using cached pandas-2.3.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.3.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting python-dateutil>=2.8.2 (from pandas)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached pandas-2.3.2-cp313-cp313-win_amd64.whl (11.0 MB)
Using cached numpy-2.3.3-cp313-cp313-win_amd64.whl (12.8 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, six, numpy, python-dateutil, pandas
Successfully installed numpy-2.3.3 pandas-2.3.2 python-dateutil-2.9.0.post0 pytz-2025.2 six-1.17.0 tzdata-2025.2
(.venv) PS D:\Sigma6.0\SIH\Final\Lens\Lens\LensClone\backend> python data_preprocessor.py
Traceback (most recent call last):
  File "D:\Sigma6.0\SIH\Final\Lens\Lens\LensClone\backend\data_preprocessor.py", line 7, in <module>
    df = df.dropna(subset=['water_level_mbgl'])
  File "D:\Sigma6.0\SIH\Final\Lens\Lens\LensClone\.venv\Lib\site-packages\pandas\core\frame.py", line 6677, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['water_level_mbgl']
(.venv) PS D:\Sigma6.0\SIH\Final\Lens\Lens\LensClone\backend> 